### PR TITLE
Travis CI: Run tests on both Linux and macOS

### PR DESCRIPTION
**Pull request by cclauss**
http://www.pyinstaller.org

### CODE REVIEW

**Comment by nanoric** [comment]
Thank you for providing a macos example! I really want it.
But it seems that travis-ci is failed to parse .travis.yaml. How to fix it?
And, 
I really want to test if our project can run under mscos but we don't want to build a standalone app or executalbe. It is necessary to use pyinstaller?

**Comment by cclauss** [comment]
Pyinstaller is optional.  I will change the PR to focus on adding macOS without pyinstaller.

**Comment by nanoric** [comment]
Thanks for your Pull Request. OSX tests is currently added into .travis.yml.

**Comment by vnpy** [comment]
已经手动修改添加支持

**Pull request closed without merging**
