### PR TITLE
Remove trailing whitespace with reindent.py

### PR DESCRIPTION
**Pull request by cclauss**
https://github.com/python/cpython/blob/master/Tools/scripts/reindent.py   This PR is the result of running __reindent -r .__  Merging this PR first should make it easier to understand and review #1244.

### CODE REVIEW

**Comment by cclauss** [comment]
@blueyed I tried your __sed__ trick but could not make it work on my Mac.  Does it produce identical results?

**Comment by blueyed** [comment]
It seems to do more.
On MAcOS you might need the GNU sed (or rewrite it), dunno.

**Comment by cclauss** [comment]
So pycodestyle, pyflakes, flake8, etc. will raise a __W292__ on all files processed with the sed trick?

https://pycodestyle.readthedocs.io/en/latest/intro.html#error-codes

**Comment by blueyed** [comment]
No.
I've meant your PR/reindent.py does more than the `sed` script I've used that only removed trailing spaces (but not newline characters)..
When skimming your PR I've seen that it also removes empty lines at the end of files (which is different from a missing newline character at the end of the file, which W292 seems to be about).

reindent.py/black/autopep8 are more involved.
For web.py I just wanted to get rid of all the trailing whitespace, but not change anything else.
But reindent.py appears to be a good tool for this in general (whereas black is nice, but does a lot of changes initially).

**Comment by cclauss** [comment]
Now I understand.  Thanks for the explanation.

**Comment by vnpy** [comment]
代码将在v2.0中重构，关闭PR。

**Pull request closed without merging**
